#!/usr/bin/bash

SCRIPTDIR=$(dirname 0)
SUBMISSIONDIR=$SCRIPTDIR/submissions

# Repeat search-open procedure forever
while true
do
	# Search for a student name, break if the search is canceled with CTRL+C
	FZFRES=$(fd .*py $SUBMISSIONDIR | fzf)
	if [ ! $PIPESTATUS -eq 0 ]
	then
		break;
	fi
	FILENAME=$(basename $FZFRES)

	# Move to main directory so vim can find the configs
	nvim "$SUBMISSIONDIR/$FILENAME"

	# Keep running python program until it's broken with an error
	while true
	do
		python "$SUBMISSIONDIR/$FILENAME"
		if [ ! $? -eq 0 ]
		then
			break;
		fi
	done

	# Wait for an enter keypress to continue
	printf "%s " "Press enter to continue"
	read ans
done

